version: "3"
services:
  postgresql:
    image: postgres:latest
    container_name: socket_test
    restart: always
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
      TZ: Asia/Seoul

